name: "PR Workflow ${{ github.event.pull_request.number}}"
on:
  pull_request:

jobs:
  MyJob1:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
