name: "Run Linter"
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      enviornment:
        default: "dev"
        required: true

jobs:
  LinterChecker:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      
      - name: 'Install Dependencies'
        run: |
          pip install -r reqirements.txt